schema_version: 1

context:
  version: "2.4.1"

package:
  name: tadc
  version: ${{ version }}

source:
  url: https://github.com/NOAA-CO-OPS/CO-OPS-Tidal-Analysis-Datum-Calculator/archive/v${{ version }}.tar.gz
  sha256: ef1e251cc028fb553feb2e1ff6096edf5f79de534052176d8dc217d9a3e7192e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}
    - matplotlib-base
    - numpy
    - pandas >=2.0.3
    - python-dateutil
    - requests
    - scipy

tests:
  - python:
      imports:
        - tadc
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/NOAA-CO-OPS/CO-OPS-Tidal-Analysis-Datum-Calculator
  summary: The Tidal Analysis Datum Calculator (TADC) computes tidal datums from a water level data time series.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
